# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37f2de8b963d2c6a614d9204b60b2af2c17cf4de72bd3ca358300f36a3c1599dceedeb9bd801742fb94c21546c105929ea48c6824a74e30d8e74b8f5defad6f7

test:
  secret_key_base: c27c90466ec1ef3c7fcb9d7d8273424bfeb1821b56ced296ab622f73eb70511ee574e11021253dc55b105ba842cafb5f8f52e00904e4ec936d629e9b58fefe15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
